# Generated by Django 4.2.16 on 2025-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiondocument',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectiondocument',
            name='confidence_score',
            field=models.IntegerField(help_text='Confidence score from 0 to 100, in %', null=True),
        ),
        migrations.AddField(
            model_name='detectiondocument',
            name='is_genuine',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='confidence_score',
            field=models.IntegerField(help_text='Confidence score from 0 to 100, in %', null=True),
        ),
    ]
