# Generated by Django 4.2.16 on 2025-01-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detectiondocument_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectiondocument',
            name='is_genuine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detectiondocument',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detectiondocument',
            name='recording_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
