# Generated by Django 4.2.16 on 2025-01-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_detectiondocument_is_genuine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectiondocument',
            name='confidence_score',
            field=models.FloatField(help_text='Confidence score from 0 to 100, in %', null=True),
        ),
    ]
