# Generated by Django 4.2.16 on 2025-01-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_detectiondocument_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiondocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detectiondocument',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
